<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buscar servios</name>
   <tag></tag>
   <elementGuidId>ca28c787-b811-4a5b-aa28-61219a5729e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'search-input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'search-input' and @placeholder = 'Buscar serviços...']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Buscar serviços...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>948b55fe-8e10-4f5d-b6e9-41854acb2167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14ceb3da-0fce-4dfd-8f13-07167fd6ffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>e31c224a-2fa0-4b71-9177-284f1e785ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar serviços...</value>
      <webElementGuid>1a11378e-d571-4ee1-b1dc-edfa67fb5d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>filterCategories(this.value)</value>
      <webElementGuid>0b8e1985-1b78-4a21-9b31-f65bead951dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d47df189b675247b5b3fcce5a9b577d9</value>
      <webElementGuid>8c7f685b-e275-40f9-a88a-6c589f38593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'search-input']</value>
      <webElementGuid>f8d0a05f-4bb8-4826-8d18-90964d40a114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'search-input']</value>
      <webElementGuid>8b397514-dd93-4285-a5ad-8c89f5e3ac3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search-input' and @placeholder = 'Buscar serviços...']</value>
      <webElementGuid>a69399f9-2040-4c1c-9de6-f3022dcbe947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
