<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Agendamentos</name>
   <tag></tag>
   <elementGuidId>83d05896-a8a9-413f-bc04-d0b9beed936d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.desktop-only</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Agendamentos' or . = 'Agendamentos')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' desktop-only ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Agendamentos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e264d7a8-01d9-4df7-baf0-e3c4268b62b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-only</value>
      <webElementGuid>d479b3e2-1f32-48cc-bfc3-0ee208909c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agendamentos</value>
      <webElementGuid>c4602d95-1f63-4858-b47b-ec977654d1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c5952e5298fabd0cd9d3a4d4cd0c43da</value>
      <webElementGuid>0acbff9a-8ddf-404c-acb5-5aedffb2b916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' desktop-only ')]</value>
      <webElementGuid>e2912a6b-8d93-4a6f-a947-deb212c453c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' desktop-only ')]</value>
      <webElementGuid>df0e4b10-0bf8-4d72-aba1-ce38343f2522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Agendamentos' or . = 'Agendamentos')]</value>
      <webElementGuid>f7b2071b-c4f9-42d6-9921-7e48c83ab20b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
