analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3563692,"name"\:"Cellphone Shop Trial \#3563692","teamId"\:3576536,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3551614,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3576536,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=false
