<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cachorro</name>
   <tag></tag>
   <elementGuidId>e782567f-73ca-4d88-9f35-8ef3eaf3b0db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[src=&quot;assets\/cao\.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@src = 'assets/cao.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inputs_animais >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>494afd9b-981f-4ce7-ba94-70c1ef03cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/cao.png</value>
      <webElementGuid>19cc1e47-dab0-4426-b9a3-7fb0610f2dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30px</value>
      <webElementGuid>9e1fa547-2b5f-4127-a7b0-77ba7ad5642a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-65ec793adb4cd6ba3452a6461fce9ea7</value>
      <webElementGuid>59e422c1-aebe-45f0-83c2-1d330430e65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@src = 'assets/cao.png']</value>
      <webElementGuid>3284c1c0-3305-4841-9d0c-559577896870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@src = 'assets/cao.png']</value>
      <webElementGuid>157a29ac-5667-4102-a2bc-27914a93144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/cao.png']</value>
      <webElementGuid>0dca2a81-f08d-4407-89e3-5feff8775745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
