<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input_data</name>
   <tag></tag>
   <elementGuidId>e084b59b-7f1e-4af2-9b28-c9f820c659ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'input_data']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#input_data</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4948af76-6961-4db1-8bf5-1782642de1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6d29deb2-8cba-4a6d-8d7e-7c3c6d468300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_data</value>
      <webElementGuid>0b5a4c08-bf1b-40d0-bf10-a5cacee2095a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>36f4b15e-ba78-4eef-8bd3-c64a78a50f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7a23d30e641d1bf585d0ae7d4426828e</value>
      <webElementGuid>869742bd-dbf9-469b-a469-111636700239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'input_data']</value>
      <webElementGuid>bbe4da69-5b06-4eca-8677-838240534315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'input_data']</value>
      <webElementGuid>009a2540-cbd4-4bbf-ba50-67db4b1ce57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'input_data' and @name = 'data']</value>
      <webElementGuid>eca338f8-09b0-44b6-a36d-f1d92d912869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
