<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_11_00</name>
   <tag></tag>
   <elementGuidId>33e3b666-57f0-403c-b312-94a6d969f01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.label_hora:nth-child(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 8)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;11:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3192629a-680b-4670-bf27-0bde98f60957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>7dcca083-65aa-4084-8a82-a3183d9b4e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_hora</value>
      <webElementGuid>4d3ffbfc-bd78-4ed9-a54d-efe6b7468440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11:00</value>
      <webElementGuid>956ad434-d81d-4a75-ab89-a4ba3c69e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1c73de0bc592b49f39f7f8a8a6bf35de</value>
      <webElementGuid>6f530656-d65c-42ef-870f-c9d77a20f398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 8)]</value>
      <webElementGuid>f7372b18-b269-4622-9d10-4cda9cfdd507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 8)]</value>
      <webElementGuid>d87e7988-90f9-41c1-9f1b-4db5a983bcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '11:00' or . = '11:00')]</value>
      <webElementGuid>ae58f64f-940d-48d3-b1ae-bd859303b3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
