<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mdio</name>
   <tag></tag>
   <elementGuidId>3bda7c7f-f9f5-431e-a42d-0a9480788afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;medio&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'medio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Médio' or . = 'Médio')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Médio&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7670c029-232a-4b78-be26-0af41e7c02ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>medio</value>
      <webElementGuid>bafb8f5b-a1ac-4d21-8306-83c59deb9c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_porte</value>
      <webElementGuid>399a3555-acb1-4d26-b560-a144e464a115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Médio</value>
      <webElementGuid>c325291a-8b05-4d36-b933-8c160c7eade5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ee1481c40492ddd0b7dc21c196e940eb</value>
      <webElementGuid>9849773c-6680-4258-98d6-75497dad74f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'medio']</value>
      <webElementGuid>cdd722bf-69ab-478d-bfdc-37624dc05856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'medio']</value>
      <webElementGuid>a1309e63-c0a5-419c-9043-291a66ca72f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Médio' or . = 'Médio')]</value>
      <webElementGuid>83287e69-4c18-41e2-a5d0-1162433f5af6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
