<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_09_00</name>
   <tag></tag>
   <elementGuidId>9c5450c1-d8cb-477f-b7af-90b3a7419e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.label_hora:nth-child(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 4)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '09:00' or . = '09:00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;09:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6f94aba2-3780-41b4-a27d-2686a7b1b392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>c498d374-70c8-4fb6-bc8f-8f03627f0230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_hora</value>
      <webElementGuid>6d0ef26e-1b3d-4641-b971-eb763744f90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>3bbf6536-a01a-4e21-8d5a-d4c2b2f000b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-76aa562cb574a928e9f0dc68871d40a1</value>
      <webElementGuid>7b693cd1-3fea-4141-bc32-8b0060a806a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 4)]</value>
      <webElementGuid>7d5a8244-b23d-4b58-8e18-69c942c30eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 4)]</value>
      <webElementGuid>bdf7690a-c4d4-4d22-a974-9b192d88ca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '09:00' or . = '09:00')]</value>
      <webElementGuid>8b7094e6-d5d9-4337-b496-eaa9588f7028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
