<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_08_00</name>
   <tag></tag>
   <elementGuidId>a93f8cca-0592-4b0f-b2e8-46ee4dd97a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.label_hora:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 2)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;08:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b6fb76af-d28f-4398-bb8c-846075f28066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3b5e1cb7-dcb9-45ce-ac90-786338b6f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_hora</value>
      <webElementGuid>cacd4fe5-72b1-4eb7-b03f-c9b77c47de74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>08:00</value>
      <webElementGuid>5cc18141-ee80-4cb9-9d3c-cca9b3a9e172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fda73f29c68e8f6a12081600c395ae53</value>
      <webElementGuid>b5b17c47-82ce-4b18-a80a-7fe9b937b9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 2)]</value>
      <webElementGuid>cd5a2ad7-a537-4752-8a79-a9d934f3741c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 2)]</value>
      <webElementGuid>710a3e44-55a6-47b1-93f1-74f0481bed24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '08:00' or . = '08:00')]</value>
      <webElementGuid>f8947d72-0047-4fea-b6ff-c8f27594e7cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
