<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Grande</name>
   <tag></tag>
   <elementGuidId>f239cd3e-9eac-44d7-94d9-36cfe8b75ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;grande&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'grande']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Grande&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0692b3f1-7dc6-4a1e-8763-34c3a7338117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>grande</value>
      <webElementGuid>ea11d9ce-a925-4d11-8f1e-6ecdc0433d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_porte</value>
      <webElementGuid>1f2fdcfd-9dde-4e12-b5d8-36186f7a0bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grande</value>
      <webElementGuid>16b9fac9-5659-4a03-a222-d89c6b9d04c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8d9cd45e90b31bf0582d63b760eb0313</value>
      <webElementGuid>3ada2503-8719-4e70-92fa-2227c5153e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'grande']</value>
      <webElementGuid>c3d402b1-f267-4af4-8bf6-97e21f8a89ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'grande']</value>
      <webElementGuid>34e9a4ba-8789-483b-aac5-3f61627d8f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Grande' or . = 'Grande')]</value>
      <webElementGuid>43f91fb9-4cba-4c14-b133-6fe1b0032740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
