<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Adulto</name>
   <tag></tag>
   <elementGuidId>ab958678-9e59-4351-8f1d-bf53f58fea1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[for=&quot;adulto&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@for = 'adulto']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Adulto' or . = 'Adulto')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Adulto&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c6f1ba57-6a96-49b0-aafa-c556d32aafd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>adulto</value>
      <webElementGuid>5506d095-2e8a-4c77-87bf-31838b2e5a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_fase</value>
      <webElementGuid>4c9575e3-4b50-465f-bdad-a352e0787894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adulto</value>
      <webElementGuid>6e0a234b-0a87-4d16-b602-e2047b0ca4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f6ae6f5b77cbec4d97b3e024e45517f8</value>
      <webElementGuid>8621ce9d-4788-444f-9a10-58216b380dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@for = 'adulto']</value>
      <webElementGuid>b5e2174e-3ab7-4242-bba0-04892091060c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@for = 'adulto']</value>
      <webElementGuid>7f83d28c-1525-4c48-a9c4-0f892dd41533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Adulto' or . = 'Adulto')]</value>
      <webElementGuid>9c603855-825e-4061-863d-b52bccd423fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
