<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_10_00</name>
   <tag></tag>
   <elementGuidId>3d75442c-c852-43ff-b33a-cca6ea1aeeb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.label_hora:nth-child(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 6)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;10:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>58bdd869-5927-4512-8ee2-947ce74df7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>50f1fd27-8388-45ee-af66-315c879e63e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_hora</value>
      <webElementGuid>980515d1-0d5f-45e3-b6ec-18c81c1effbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10:00</value>
      <webElementGuid>c99f3b72-e6b5-4ea5-9fcc-780555a04e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ac08695995b9f649e388c5e8408856b</value>
      <webElementGuid>a5a2931e-66d4-4b66-99ce-ec72fcd3ef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 6)]</value>
      <webElementGuid>35399a92-b46f-467c-8379-eaec3ec2e9aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 6)]</value>
      <webElementGuid>594e5b04-cdae-4912-97b8-c68c03e1c2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '10:00' or . = '10:00')]</value>
      <webElementGuid>2f8b3e23-b282-462b-bf30-8fc05d1c8977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
