<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_15_00</name>
   <tag></tag>
   <elementGuidId>9af3e131-47bb-447c-b522-b3ef30259a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.label_hora:nth-child(12)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 12)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;15:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>071cd6a3-50cb-4992-b6e7-25ee0905005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>5b5f7583-89ee-4197-8f97-4e5699c92742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_hora</value>
      <webElementGuid>b5c55248-a4e6-4e10-941c-947976c69546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15:00</value>
      <webElementGuid>a406759c-1e95-4c45-a610-be0d3d46e726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a857cacfdef826b0b39beef3c741e87a</value>
      <webElementGuid>2fc1ae11-37d2-42f4-a734-9362a3f5e8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 12)]</value>
      <webElementGuid>9f5ba75c-b3c8-49b3-ab47-b3d8fbc31431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' label_hora ') and (position() = 12)]</value>
      <webElementGuid>cc07efb5-1973-43e3-862c-da895a1c7a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '15:00' or . = '15:00')]</value>
      <webElementGuid>ab637450-7221-4ae2-81c7-915f68b6578a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
