<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cadastre-se</name>
   <tag></tag>
   <elementGuidId>74237303-8386-4f63-8922-114640a70da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;cadastro\.html&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'cadastro.html' and (text() = ' Cadastre-se' or . = ' Cadastre-se')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'cadastro.html']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cadastre-se&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9498ca40-dc3d-4a33-8b6a-b892b519f320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>cadastro.html</value>
      <webElementGuid>8b078e1d-9e25-403e-ae6b-2796cbfe42e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cadastre-se</value>
      <webElementGuid>1127fbbc-f2cb-4269-bc13-23a8a61e70a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-96a1c8c868c1ea29a3e3962247b96627</value>
      <webElementGuid>e0555252-9c81-4b30-abb5-16479fba27e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'cadastro.html']</value>
      <webElementGuid>f70dcb27-4772-469e-ad7a-5eb6be31fc48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'cadastro.html']</value>
      <webElementGuid>efb173a3-4089-44fe-8a6c-2d25b096a288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'cadastro.html' and (text() = ' Cadastre-se' or . = ' Cadastre-se')]</value>
      <webElementGuid>14d8dfe0-3d7b-4536-bf71-10f7b232db74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
