<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite seu email</name>
   <tag></tag>
   <elementGuidId>752d60fb-ac27-49f1-82f7-9129ccdfe76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email' and @id = 'email_login' and @name = 'email_login' and @placeholder = 'Digite seu email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'email_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite seu email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70f9dfb0-8958-4d63-be06-58cfd3c2f5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6c6e5341-11d4-4c58-9255-c7cef1d424f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_login</value>
      <webElementGuid>bdbabd24-3ff0-48a8-aed8-231d4f3b6194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_login</value>
      <webElementGuid>75a577de-1ab3-40fa-9b40-517ad5d5148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite seu email</value>
      <webElementGuid>db037afe-ad29-4809-9220-7adc57df4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-42678660e7f1ac7f969d3e4935e69ba7</value>
      <webElementGuid>ebc338db-f7e4-4389-9de5-ab2b6cb09aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'email_login']</value>
      <webElementGuid>0819bed0-9851-4127-b5c0-abe1b1fb704d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'email_login']</value>
      <webElementGuid>584386cf-bcd2-44df-932f-b2b4e1124ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email_login' and @name = 'email_login' and @placeholder = 'Digite seu email']</value>
      <webElementGuid>672c7503-90ec-4e4d-8aef-f6a84caf971c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
