<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite sua senha</name>
   <tag></tag>
   <elementGuidId>2b6f2f78-ad89-4c92-bd9a-6610a994467f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @id = 'senha_login' and @name = 'senha_login' and @placeholder = 'Digite sua senha']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'senha_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#senha_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite sua senha&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f347926-cfa6-405d-ade1-4a260847f59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>502a30a1-8343-4619-8149-1cf97fe237a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>senha_login</value>
      <webElementGuid>fbeb4fc4-ed4e-4201-9680-62273647f148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha_login</value>
      <webElementGuid>6927dd51-af2d-49b2-95d8-53186ad56bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite sua senha</value>
      <webElementGuid>2a97539b-a83e-432d-89cb-3b4805c9432b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f702a394aaf4f5036e63f59b7ad197d</value>
      <webElementGuid>fa751b9d-d5d0-4ff2-9afb-f8750747a3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'senha_login']</value>
      <webElementGuid>99219501-a95a-488d-b24e-5e7d36bad4ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'senha_login']</value>
      <webElementGuid>40b69beb-781d-4d63-ae99-cd135ffd3f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'senha_login' and @name = 'senha_login' and @placeholder = 'Digite sua senha']</value>
      <webElementGuid>15438f9f-7054-45d2-bbef-2d9373325793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
