<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Incio</name>
   <tag></tag>
   <elementGuidId>cdc348f3-706a-47b6-9712-e7883e2faf40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.nav-links [href=&quot;index\.html&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-links ')]//*[@href = 'index.html']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Início&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d37c289a-ac2a-4dba-8d96-3ab1a0580958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.html</value>
      <webElementGuid>72e6dacf-3a0e-40f8-a211-a4c5412317dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Início</value>
      <webElementGuid>2b14fa0c-76a8-443d-bc76-415206cc0d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ae998a7ccbebbc733ed62340320ff6f3</value>
      <webElementGuid>c797288b-f142-4489-aed8-f316b10b95b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-links ')]//*[@href = 'index.html']</value>
      <webElementGuid>917cc506-771a-4328-9117-f226f5c2f3dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' nav-links ')]//*[@href = 'index.html']</value>
      <webElementGuid>6b18e85e-b092-4929-bfcc-124810a1fdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.html' and (text() = 'Início' or . = 'Início')]</value>
      <webElementGuid>75fe3297-51c4-44f3-893c-dc9c8b7cf922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
