<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cadastrar</name>
   <tag></tag>
   <elementGuidId>8ee71ba0-0cee-4c61-a894-ef7367f4cf0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cadastrar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cadastrar']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'cadastrar' and (text() = 'Finalizar Cadastro' or . = 'Finalizar Cadastro')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finalizar Cadastro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72946ce6-c83c-4a63-86f1-6e471bd9c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c0cf28be-8705-4a53-8bdb-483ce2bd442f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cadastrar</value>
      <webElementGuid>381d3764-8039-4cd1-8725-9d04982ba2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Finalizar Cadastro</value>
      <webElementGuid>18a17894-c329-470b-b87d-9c13eb8c5fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-27d405703a696ec1377a8550d07e0425</value>
      <webElementGuid>c04c7808-fdbd-4557-b664-a4e6829643af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cadastrar']</value>
      <webElementGuid>31370b8e-96aa-4c0a-a680-62497c1c3ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cadastrar']</value>
      <webElementGuid>8dc271b0-ce23-4374-9e32-b65b5ccc1244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'cadastrar' and (text() = 'Finalizar Cadastro' or . = 'Finalizar Cadastro')]</value>
      <webElementGuid>c6ae0241-0e2a-4e2f-8b2e-3537907c99d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
