<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_000.000.000-00</name>
   <tag></tag>
   <elementGuidId>814874f3-6126-4220-90f1-5e2dcc4c2a07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cpf']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @id = 'cpf' and @name = 'cpf' and @placeholder = '000.000.000-00']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;000.000.000-00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0baebcf3-26f9-4e41-a7b3-b5d5b6c2f6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ed9644c1-1057-4b64-8f8d-86522c5d07a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpf</value>
      <webElementGuid>7a26f7d8-444f-4f7c-9241-3868549024bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpf</value>
      <webElementGuid>b7dd6c8b-8c74-4867-b493-95c154a8f509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000.000.000-00</value>
      <webElementGuid>39c1b6d2-a9cd-49f2-a709-1a1742cdc6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>erro_cpf()</value>
      <webElementGuid>79a07fa2-4857-4e9b-9ee6-7c193e5a4008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c94c6855ce071ef9378d9b88ef401cc3</value>
      <webElementGuid>58537309-df86-4fa9-b298-bc5d14b615f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cpf']</value>
      <webElementGuid>d7b05b04-65b2-4dbb-baab-a1932b564c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cpf']</value>
      <webElementGuid>8f8eeaff-ec42-477f-8a68-dd61131349e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'cpf' and @name = 'cpf' and @placeholder = '000.000.000-00']</value>
      <webElementGuid>0a530b39-53ba-40b3-bcc1-70217e883262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
