<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite a idade do seu pet</name>
   <tag></tag>
   <elementGuidId>a24799c4-6732-4ce3-9d95-59c16583884b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idade_pet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'idade_pet']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'idade_pet' and @name = 'idade_pet' and @placeholder = 'Digite a idade do seu pet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite a idade do seu pet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d5b872a-6977-4e3b-8fe6-cce499c1f63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b7cf170-f126-430c-a18d-12de81c31753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idade_pet</value>
      <webElementGuid>db91b44d-07bc-4a83-aa50-f025ca3c1955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idade_pet</value>
      <webElementGuid>24164a75-056e-4652-a033-b5727372dcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite a idade do seu pet</value>
      <webElementGuid>57504eef-7e46-4e7c-8f3b-de9a62cafb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>function_idade_pet()</value>
      <webElementGuid>9d1b1810-3451-4548-b8dc-5a1e851aa70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2ff7b6a92c9278d0c4e3fbf27d2e1de2</value>
      <webElementGuid>488429e6-744f-466f-9143-d420d196147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'idade_pet']</value>
      <webElementGuid>016dcc0b-a3a1-4f7e-87b3-74d415e87424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'idade_pet']</value>
      <webElementGuid>7194e40f-72c3-4665-addd-939aa16c7f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'idade_pet' and @name = 'idade_pet' and @placeholder = 'Digite a idade do seu pet']</value>
      <webElementGuid>55b38f09-5a73-4844-a42a-ef6449ef67a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
