<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seu nome completo</name>
   <tag></tag>
   <elementGuidId>8de5fc04-d25e-40b9-a9bd-9d5bed15a41e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nome_dono']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'nome_dono' and @name = 'nome_dono' and @placeholder = 'Seu nome completo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nome_dono</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Seu nome completo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd2189ef-a6be-42d8-ad9c-42723707178b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30d2761e-f1a3-4491-8018-74e92e49f96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nome_dono</value>
      <webElementGuid>3dfb0c9e-dcac-4eca-b90c-b5706dff5ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nome_dono</value>
      <webElementGuid>a2155a31-0fbf-4859-9e96-f997df0aa7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Seu nome completo</value>
      <webElementGuid>128bd771-e818-4b9d-b1b4-e571d9d6e9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>erro_nome()</value>
      <webElementGuid>4ceec3f3-f99f-4691-9048-82e8044be600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-78ff71d132caa6c1f1a572556d9d1576</value>
      <webElementGuid>76936a97-1e6e-47ff-9797-20d73d8cb735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nome_dono']</value>
      <webElementGuid>860cca0d-2050-4bb5-816d-d36b3f6ad1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nome_dono']</value>
      <webElementGuid>df97630a-8fc7-4265-885b-66cf44021f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nome_dono' and @name = 'nome_dono' and @placeholder = 'Seu nome completo']</value>
      <webElementGuid>1b12d17d-3e6d-49e1-968d-51cf6a99e8b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
