<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite o nome do seu Pet</name>
   <tag></tag>
   <elementGuidId>e90d7c61-9b03-46ea-b16c-a063b49247df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nome_pet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nome_pet']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'nome_pet' and @name = 'nome_pet' and @placeholder = 'Digite o nome do seu Pet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite o nome do seu Pet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9d04731-9e17-4c42-8d7a-e24afe7bcea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>873003ec-e735-4d2d-9027-b2344c620b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nome_pet</value>
      <webElementGuid>3f009c6a-4e47-4dd6-a538-3e2673540b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nome_pet</value>
      <webElementGuid>b3d4c57f-305a-4b78-9414-99fbcc003ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite o nome do seu Pet</value>
      <webElementGuid>19cee8e4-c411-47d8-8573-491e62307e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>function_nome_pet()</value>
      <webElementGuid>c07a2c38-ccbf-4cc0-a552-a44091da962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b7e4c61d8896665efcc7087d1ec9823</value>
      <webElementGuid>0ff34d17-49ff-4079-8bb3-7b5accbe876e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nome_pet']</value>
      <webElementGuid>b8fe64d1-610f-4404-8400-36df61d807fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nome_pet']</value>
      <webElementGuid>cef0590c-6cab-48e2-8e65-029de1126978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nome_pet' and @name = 'nome_pet' and @placeholder = 'Digite o nome do seu Pet']</value>
      <webElementGuid>c44ab9d8-0206-42f3-9695-e12e19ea8da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
