<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Digite o seu telefone</name>
   <tag></tag>
   <elementGuidId>149b8166-17c4-4833-89f5-c32b26172ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telefone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'telefone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @id = 'telefone' and @name = 'telefone' and @placeholder = 'Digite o seu telefone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Digite o seu telefone&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75f3ecaf-afca-4613-92ab-5fd1f199991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2955598d-be41-48b8-88c2-16acaafba45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telefone</value>
      <webElementGuid>1fc811bb-7da2-47b2-b172-1a51459bf9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telefone</value>
      <webElementGuid>07252c20-2b41-468d-a8ae-3caa28c830c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Digite o seu telefone</value>
      <webElementGuid>63373807-d570-4917-aa49-0f5802ec3378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>function_erro_telefone()</value>
      <webElementGuid>62d6c954-191d-4f61-9ff0-6e586c2e3b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-80575e743efc103d9a973b3899c96001</value>
      <webElementGuid>adf6bb59-880e-4de7-8693-3a7dd60558e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'telefone']</value>
      <webElementGuid>52adb1fe-4ad5-4fe7-bf0f-79bf3473d3fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'telefone']</value>
      <webElementGuid>84415c37-98fc-404a-8482-b722de29031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'telefone' and @name = 'telefone' and @placeholder = 'Digite o seu telefone']</value>
      <webElementGuid>d4028709-329f-4b45-a976-08dc0815183e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
