<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Senha</name>
   <tag></tag>
   <elementGuidId>336d1b38-9dce-4c06-98f6-3ca6cd5cae17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#senha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'senha']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @id = 'senha' and @name = 'senha' and @placeholder = 'Senha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Senha&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4eb0d1f3-2053-470b-8b4d-2249853968ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c62b3e1a-71aa-4278-b0ea-21b55af2e08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>f464d4eb-7351-4653-a978-029da582eac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>senha</value>
      <webElementGuid>257a9ddc-8a13-4921-9c3d-d0540f060a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>378b01f6-0688-4aaf-95ce-a461abea9264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>erro_repetir_senha()</value>
      <webElementGuid>ac8d77f9-45fe-41fd-9e19-d9bf1a6c04a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3022e540bd405fcfb637f310430dec25</value>
      <webElementGuid>f5129c52-b8b9-4f81-9f36-731d305344ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'senha']</value>
      <webElementGuid>bfec4bce-b7cc-44e5-ac7b-9c67aa7993da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'senha']</value>
      <webElementGuid>2b22bd6b-c2c9-4d10-89e1-48aa0910584d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'senha' and @name = 'senha' and @placeholder = 'Senha']</value>
      <webElementGuid>d9d57029-e81c-40ab-a4e5-8c1dd05c2046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
