<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sua Cidade</name>
   <tag></tag>
   <elementGuidId>ce1129b8-ee96-484e-af37-92829b9cbd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cidade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cidade']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'cidade' and @name = 'cidade' and @placeholder = 'Sua Cidade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Sua Cidade&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf6561f5-f8f6-45b8-a2a6-21633a531682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f9a6237-5ac4-46e2-bc00-773f5f0e0894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cidade</value>
      <webElementGuid>0c31148f-51eb-40fc-913b-6e293bbd9012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cidade</value>
      <webElementGuid>73ec0d56-20e8-4721-abd4-3a4474c94356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sua Cidade</value>
      <webElementGuid>eb74da18-6699-4ea6-99fc-67901bab58f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>erro_cidade()</value>
      <webElementGuid>8dfe16dc-9f80-4d13-a20e-a67c22a5dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-96e34c9e1c0c66e91b124025c07ed74d</value>
      <webElementGuid>4037ad31-953e-42bb-80a8-4c4611024037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cidade']</value>
      <webElementGuid>72abd17d-9895-4612-8052-5066c5a53635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cidade']</value>
      <webElementGuid>471fbfcf-a051-4b83-abd1-9d396057c9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cidade' and @name = 'cidade' and @placeholder = 'Sua Cidade']</value>
      <webElementGuid>7097adc5-2bc7-4b84-a02c-db47813af231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
